# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-12 20:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aa_stripe', '0003_auto_20170608_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stripecharge',
            name='stripe_charge_id',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='stripecustomer',
            name='stripe_customer_id',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='stripesubscription',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='stripesubscriptionplan',
            name='currency',
            field=models.CharField(default='USD', help_text='3 letter ISO code, default USD, https://stripe.com/docs/api#create_plan-currency', max_length=3),
        ),
    ]
