# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-09 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aa_stripe', '0012_auto_20170908_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripesubscription',
            name='at_period_end',
            field=models.BooleanField(default=False),
        ),
    ]
