# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-15 13:10
from __future__ import unicode_literals

import jsonfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aa_stripe', '0017_stripecharge_manual_charge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stripecoupon',
            name='metadata',
            field=jsonfield.fields.JSONField(blank=True, help_text='Set of key/value pairs that you can attach to an object. It can be useful for storing additional information about the object in a structured format.', null=True),
        ),
    ]
