# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-11 15:44
from __future__ import unicode_literals

import django.core.validators
import django.db.models.deletion
import jsonfield.fields
from django.db import migrations, models


def migrate_old_cards(apps, schema_editor):
    StripeCard = apps.get_model("aa_stripe", "StripeCard")
    StripeCustomer = apps.get_model("aa_stripe", "StripeCustomer")
    for customer in StripeCustomer.objects.exclude(stripe_js_response=""):
        try:
            card_data = customer.stripe_js_response["card"]
            card = StripeCard.objects.create(stripe_card_id=card_data["id"], last4=card_data["last4"],
                                             exp_month=card_data["exp_month"], exp_year=card_data["exp_year"],
                                             stripe_response=customer.stripe_js_response, customer=customer)
            customer.default_card = card
            customer.save()
        except KeyError as e:
            print("Cannot migrate customer card, key error: {}".format(e))


class Migration(migrations.Migration):

    dependencies = [
        ('aa_stripe', '0017_stripecharge_manual_charge'),
    ]

    operations = [
        migrations.CreateModel(
            name='StripeCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('stripe_response', jsonfield.fields.JSONField(default=dict)),
                ('stripe_card_id', models.CharField(help_text='Unique card id in Stripe', db_index=True, max_length=255)),
                ('last4', models.CharField(help_text='Last 4 digits of the card', max_length=4)),
                ('exp_month', models.PositiveIntegerField(help_text='Two digit number representing the card’s expiration month', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('exp_year', models.PositiveIntegerField(help_text='Four digit number representing the card’s expiration year', validators=[django.core.validators.MinValueValidator(1900)])),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aa_stripe.StripeCustomer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='stripecustomer',
            name='default_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='aa_stripe.StripeCard'),
        ),
        migrations.RunPython(migrate_old_cards)
    ]
