# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-10 19:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aa_stripe', '0020_stripecharge_statement_descriptor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stripecharge',
            name='stripe_refund_id',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
    ]
