# Generated by Django 4.2.20 on 2025-04-29 05:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


remove_indexes = [
    "DROP INDEX CONCURRENTLY IF EXISTS aa_stripe_stripecharge_user_id_6f76c244",
    "DROP INDEX CONCURRENTLY IF EXISTS aa_stripe_stripecharge_stripe_refund_id_78d16b7f_like",
    "DROP INDEX CONCURRENTLY IF EXISTS aa_stripe_stripecharge_stripe_refund_id_78d16b7f",
    "DROP INDEX CONCURRENTLY IF EXISTS aa_stripe_stripecharge_stripe_charge_id_86aca19a",
    "DROP INDEX CONCURRENTLY IF EXISTS aa_stripe_stripecharge_stripe_charge_id_86aca19a_like",
    "DROP INDEX CONCURRENTLY IF EXISTS aa_stripe_stripecharge_customer_id_a6cd951b",
]


def drop_indexes_postgresql(apps, schema_editor):
    """
    This function drops indexes for PostgreSQL database.
    It will NOT run on SQLite during testing as it does NOT support:
    - DROP INDEX CONCURRENTLY
    - IF EXISTS
    """
    if schema_editor.connection.vendor != "postgresql":
        return  # Skip for SQLite or other DBs

    for sql in remove_indexes:
        schema_editor.execute(sql)


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("aa_stripe", "0022_stripecharge_amount_refunded"),
    ]
    atomic = False  # CONCURRENTLY cannot run inside a transaction block

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    drop_indexes_postgresql,
                    reverse_code=migrations.RunPython.noop,
                ),
            ],
            state_operations=[
                migrations.AlterField(
                    model_name="stripecharge",
                    name="customer",
                    field=models.ForeignKey(
                        db_index=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="aa_stripe.stripecustomer",
                    ),
                ),
                migrations.AlterField(
                    model_name="stripecharge",
                    name="stripe_charge_id",
                    field=models.CharField(blank=True, max_length=255),
                ),
                migrations.AlterField(
                    model_name="stripecharge",
                    name="stripe_refund_id",
                    field=models.CharField(blank=True, max_length=255),
                ),
                migrations.AlterField(
                    model_name="stripecharge",
                    name="user",
                    field=models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stripe_charges",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        )
    ]
