# Generated by Django 4.2.20 on 2025-04-29 05:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('aa_stripe', '0022_stripecharge_amount_refunded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stripecharge',
            name='customer',
            field=models.ForeignKey(db_index=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aa_stripe.stripecustomer'),
        ),
        migrations.AlterField(
            model_name='stripecharge',
            name='stripe_charge_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='stripecharge',
            name='stripe_refund_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='stripecharge',
            name='user',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='stripe_charges', to=settings.AUTH_USER_MODEL),
        ),
    ]
